Use Python 3.11 to fix RtD build issue
Current default Python 3 is 3.12, which brings incompatibilities due to
removal of distutils.

ModuleNotFoundError: No module named 'distutils'

Not ready to require Python 3.12, so for now, pin to version 3.11.